default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
